# Generated by Django 5.1.3 on 2024-11-18 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_contacts_contact_alter_appointments_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='datetime',
            new_name='date',
        ),
    ]
